# the keyboard devices it reads from, if no devices are specified, it reads from all
devices:
# - "/dev/input/by-id/SOME_KEYBOARD_REPLACE_ME-event-kbd"

# startCommand: "setxkbmap de"

baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 200.0
mouseAccelerationCurve: 2.0

startMouseSpeed: 0.0

mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
  - name: initial
    bindings:
      space: tap-hold space ; toggle-layer thuan_fly_keys ; 185
      q: tap-hold q ; toggle-layer mouse ; 185
      a: tap-hold-next-release a ; leftmeta ; 180
      s: tap-hold-next-release s ; leftalt ; 180
      d: tap-hold-next-release d ; leftshift ; 180
      f: tap-hold-next-release f ; leftctrl ; 180
      j: tap-hold-next-release j ; rightctrl ; 180
      k: tap-hold-next-release k ; rightshift ; 180
      l: tap-hold-next-release l ; rightalt ; 180
      semicolon: tap-hold-next-release semicolon ; rightmeta ; 180

      # capslock kinda useless for me, so i map it to esc for vim
      capslock: esc

      # key `|\` at the bottom on msi laptop keyboard, why? they put the key in this position
      102nd: leftctrl

      #####################
      # External keyboard #
      #####################

      # key menu
      compose: leftctrl
      f1: mute
      f2: volumedown
      f3: volumeup
      # mic mute, `KEY_MICMUTE` ~ micmute doesn't work, debug show key press is `f20`
      f5: f20
      f8: leftctrl+leftshift+v

  - name: mouse
    passThrough: false
    bindings:
      a: layer initial
      i: layer mouse
      l: move  1  0
      h: move -1  0
      j: move  0  1
      k: move  0 -1
      p: scroll up
      semicolon: scroll down
      leftalt: speed 4.0
      space: speed 0.3
      r: button left
      e: button middle
      w: button right

  - name: thuan_fly_keys
    passThrough: true
    bindings:
      z: reload-config

      # function key kinda far, lazy to reach out
      k1: f1
      k2: f2
      k3: f3
      k4: f4
      k5: f5
      k6: f6
      k7: f7
      k8: f8
      k9: f9
      k0: f10
      minus: f11
      equal: f12

      # gnome favorite app on dash
      a: leftmeta+k1
      s: leftmeta+k2
      d: leftmeta+k3
      f: leftmeta+k4
      g: leftmeta+k5
      q: leftmeta+k6
      w: leftmeta+k7
      e: leftmeta+k8
      r: leftmeta+k9

      # editing text

      k: up
      h: left
      j: down
      l: right
      i: home
      o: end

      # Gnome

      # resize windows
      c: rightalt+f8

      # pano clipboard extension
      v: leftmeta+leftshift+v

      # switch windows to monitor left
      comma: leftmeta+leftshift+left

      # switch windows to monitor right
      dot: leftmeta+leftshift+right

      # popshell toggle maximize
      m: leftalt+f10

      # close window
      x: leftalt+f4

      # browser

      # next tab aka `ctrl + tab`
      p: leftctrl+pagedown

      # previous tab aka `ctrl + shift + tab`
      u: leftctrl+pageup

      # go back
      leftbrace: leftalt+left

      # go forward
      rightbrace: leftalt+right
