# the keyboard devices it reads from, if no devices are specified, it reads from all
devices:
# - "/dev/input/by-id/SOME_KEYBOARD_REPLACE_ME-event-kbd"

# startCommand: "setxkbmap de"

baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 200.0
mouseAccelerationCurve: 2.0

startMouseSpeed: 0.0

mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
  - name: initial
    bindings:
      a: tap-hold a ; toggle-layer mouse ; 300
      space: tap-hold space ; toggle-layer thuan_fly_keys ; 200
      s: tap-hold s ; toggle-layer popshell ; 300
      d: tap-hold d ; toggle-layer popashell ; 300
      f: tap-hold f ; toggle-layer poptheshell ; 300

      # capslock kinda useless for me, so i map it to esc for vim
      capslock: esc

      # key `|\` at the bottom on msi laptop keyboard, why? they put the key in this position
      102nd: leftctrl

      #####################
      # External keyboard #
      #####################

      # key menu
      compose: leftctrl
      f1: mute
      f2: volumedown
      f3: volumeup
      # mic mute, `KEY_MICMUTE` ~ micmute doesn't work, debug show key press is `f20`
      f5: f20
      f8: leftctrl+leftshift+v

  - name: mouse
    passThrough: false
    bindings:
      a: layer initial
      i: layer mouse
      r: reload-config
      l: move  1  0
      h: move -1  0
      j: move  0  1
      k: move  0 -1
      p: scroll up
      semicolon: scroll down
      leftalt: speed 4.0
      space: speed 0.3
      f: button left
      d: button middle
      s: button right

  - name: thuan_fly_keys
    passThrough: true
    bindings:
      # function key kinda far, lazy to reach out
      k1: f1
      k2: f2
      k3: f3
      k4: f4
      k5: f5
      k6: f6
      k7: f7
      k8: f8
      k9: f9
      k0: f10
      minus: f11
      equal: f12

      ##################
      ## editing text ##
      ##################

      k: up
      h: left
      j: down
      l: right
      i: home
      o: end

      ###########
      ## Gnome ##
      ###########

      # resize windows
      c: rightalt+f8

      # pano clipboard extension
      v: leftmeta+leftshift+v

      # switch windows to monitor left
      comma: leftmeta+leftshift+left

      # switch windows to monitor right
      dot: leftmeta+leftshift+right

      # popshell toggle maximize
      m: leftmeta+m

      # close window
      x: leftalt+f4

      #############
      ## browser ##
      #############


      # next tab aka `ctrl + tab`
      p: leftctrl+pagedown

      # previous tab aka `ctrl + shift + tab`
      u: leftctrl+pageup

      # go back
      leftbrace: leftalt+left

      # go forward
      rightbrace: leftalt+right

  - name: popshell
    passThrough: false
    bindings:
      enter: leftmeta+enter
      h: leftmeta+h
      j: leftmeta+j
      k: leftmeta+k
      l: leftmeta+l
      u: leftmeta+leftshift+pageup
      p: leftmeta+leftshift+pagedown

  - name: popashell
    passThrough: false
    bindings:
      h: leftmeta+k1
      j: leftmeta+k2
      k: leftmeta+k3
      l: leftmeta+k4
      semicolon: leftmeta+k5
      y: leftmeta+k6
      u: leftmeta+k7
      i: leftmeta+k8
      o: leftmeta+k9
      p: leftmeta+k0

  - name: poptheshell
    passThrough: false
    bindings:
      h: leftmeta+leftshift+k1
      j: leftmeta+leftshift+k2
      k: leftmeta+leftshift+k3
      l: leftmeta+leftshift+k4
      semicolon: leftmeta+leftshift+k5
      y: leftmeta+leftshift+k6
      u: leftmeta+leftshift+k7
      i: leftmeta+leftshift+k8
      o: leftmeta+leftshift+k9
      p: leftmeta+leftshift+k0
