vim.keymap.set("i", ";b", "🔨build: ", { silent = true, buffer = 0 })
vim.keymap.set("i", ";ch", "🔩chore: ", { silent = true, buffer = 0 })
vim.keymap.set("i", ";ci", "🤖ci: ", { silent = true, buffer = 0 })
vim.keymap.set("i", ";cl", "🎨refactor(): clean code<esc>Fi)", { silent = true, buffer = 0 })
vim.keymap.set("i", ";d", "📚documents: ", { silent = true, buffer = 0 })
vim.keymap.set("i", ";fe", "🌟feature: ", { silent = true, buffer = 0 })
vim.keymap.set("i", ";fi", "🐞fix: ", { silent = true, buffer = 0 })
vim.keymap.set("i", ";p", "⚡️performance: ", { silent = true, buffer = 0 })
vim.keymap.set("i", ";rev", "⏪revert(): ", { silent = true, buffer = 0 })
vim.keymap.set("i", ";ref", "🎨refactor: ", { silent = true, buffer = 0 })
vim.keymap.set("i", ";s", "💄style: ", { silent = true, buffer = 0 })
vim.keymap.set("i", ";te", "✅test: ", { silent = true, buffer = 0 })
vim.keymap.set("i", ";to", "🤖ci(todo): add or clean", { silent = true, buffer = 0 })
