#! /usr/bin/env sh

if hash cowsay 2>/dev/null; then
  cowsay "🚀 Executing..."
  g++ main.cpp source.cpp header.h
  echo ""
  ./a.out <./input
  echo ""
  cowthink -d "🧹 Clearing..."
  rm header.h.gch
  rm a.out
else
  echo "🚀 Executing..."
  g++ main.cpp source.cpp header.h
  echo ""
  ./a.out <./input
  echo ""
  echo "🧹 Clearing..."
  rm header.h.gch
  rm a.out
fi
