#! /usr/bin/env sh

echo "set background=dark
colorscheme github_dark
" >~/dotfiles/nvim/themeControl.vim

DIRECTORY=~/dotfiles/bat

if [ -d "$DIRECTORY" ]; then
  mkdir $DIRECTORY
fi
echo "--theme=\"base16\"" >~/dotfiles/bat/config
