#! /usr/bin/env sh

echo "colorscheme github_dark

highlight HopNextKey guifg=#24292f guibg=NONE guisp=NONE gui=bold cterm=bold
" >~/dotfiles/nvim/themeControl.vim

echo "include=~/dotfiles/foot/foot_dark.ini" > ~/dotfiles/foot/themeControl.ini

DIRECTORY=~/dotfiles/bat

if [ -d "$DIRECTORY" ]; then
  mkdir $DIRECTORY
fi
echo "--theme=\"base16\"" >~/dotfiles/bat/config
