#! /usr/bin/env sh

echo "set background=light
colorscheme zenbones

highlight HopNextKey guifg=#2C363C guibg=NONE guisp=NONE gui=bold cterm=bold
" >~/dotfiles/nvim/themeControl.vim

echo "include=~/dotfiles/foot/foot_light.ini" > ~/dotfiles/foot/themeControl.ini

DIRECTORY=~/dotfiles/bat

if [ -d "$DIRECTORY" ]; then
  mkdir $DIRECTORY
fi
echo "--theme=\"GitHub\"" >~/dotfiles/bat/config
