#! /usr/bin/env sh

echo "set background=light
colorscheme github_light
" >~/dotfiles/nvim/themeControl.vim

cat ~/dotfiles/foot/foot_light.ini > ~/dotfiles/foot/foot.ini

DIRECTORY=~/dotfiles/bat

if [ -d "$DIRECTORY" ]; then
  mkdir $DIRECTORY
fi
echo "--theme=\"GitHub\"" >~/dotfiles/bat/config
