#! /usr/bin/env sh

mkdir ~/repos
cd ~/repos

mkdir thuanpham2311
cd thuanpham2311

gh repo list thuanpham2311 --limit 1000 | while read -r repo _; do
  gh repo clone "$repo" "$repo"
done

cd ..
mkdir OngDev
cd OngDev

gh repo list ongdev --limit 1000 | while read -r repo _; do
  gh repo clone "$repo" "$repo"
done

cd ..
mkdir isekaiSystem
cd isekaiSystem

gh repo list isekaiSystem --limit 1000 | while read -r repo _; do
  gh repo clone "$repo" "$repo"
done
