vim.keymap.set("i", ";b", "build(): <esc>F(a", { silent = true, buffer = 0 })
vim.keymap.set("i", ";ch", "chore(): <esc>F(a", { silent = true, buffer = 0 })
vim.keymap.set("i", ";F", "ci(): <esc>ci(", { silent = true, buffer = 0 })
vim.keymap.set("i", ";cl", "refactor(): clean code<esc>F(a", { silent = true, buffer = 0 })
vim.keymap.set("i", ";d", "documents(): <esc>F(a", { silent = true, buffer = 0 })
vim.keymap.set("i", ";fe", "feature(): <esc>F(a", { silent = true, buffer = 0 })
vim.keymap.set("i", ";fi", "fix(): <esc>F(a", { silent = true, buffer = 0 })
vim.keymap.set("i", ";p", "performance(): <esc>F(a", { silent = true, buffer = 0 })
vim.keymap.set("i", ";rev", "revert(): <esc>F(a", { silent = true, buffer = 0 })
vim.keymap.set("i", ";ref", "refactor(): <esc>F(a", { silent = true, buffer = 0 })
vim.keymap.set("i", ";s", "style(): <esc>F(a", { silent = true, buffer = 0 })
vim.keymap.set("i", ";te", "test(): <esc>F(a", { silent = true, buffer = 0 })
vim.keymap.set("i", ";to", "ci(todo): add or clean", { silent = true, buffer = 0 })
