return {
	{ "JoosepAlviste/nvim-ts-context-commentstring", enabled = false },
	{ "akinsho/bufferline.nvim", enabled = false },
	{ "catppuccin/nvim", enabled = false },
	{ "echasnovski/mini.comment", enabled = false },
	{ "echasnovski/mini.pairs", enabled = false },
	{ "folke/noice.nvim", enabled = false },
	{ "folke/persistence.nvim", enabled = false },
	{ "folke/todo-comments.nvim", enabled = false },
	{ "folke/tokyonight.nvim", enabled = false },
	{ "ggandor/flit.nvim", enabled = false },
	{ "ggandor/leap.nvim", enabled = false },
	{ "goolord/alpha-nvim", enabled = false },
	{ "nvim-lualine/lualine.nvim", enabled = false },
	{ "nvim-neo-tree/neo-tree.nvim", enabled = false },
	{ "nvim-telescope/telescope.nvim", enabled = false },
	{ "rcarriga/nvim-notify", enabled = false },
	{ "echasnovski/mini.surround", enabled = false },
	{ "vim-illuminate", enabled = false },
	{ "trouble.nvim", enabled = false },
	{ "SmiteshP/nvim-navic", enabled = false },
	{ "neoconf.nvim", enabled = false },
	{ "echasnovski/mini.bufremove", enabled = false },
	{ "nvim-tree/nvim-web-devicons", enabled = false },
}
