return {
	{ "rcarriga/nvim-notify", enabled = false },
	{ "goolord/alpha-nvim", enabled = false },
	{ "folke/tokyonight.nvim", enabled = false },
	{ "catppuccin/nvim", enabled = false },
	{ "akinsho/bufferline.nvim", enabled = false },
	{ "nvim-lualine/lualine.nvim", enabled = false },
	{ "folke/noice.nvim", enabled = false },
	{ "echasnovski/mini.pairs", enabled = false },
	{ "echasnovski/mini.comment", enabled = false },
	{ "JoosepAlviste/nvim-ts-context-commentstring", enabled = false },
	{ "nvim-neo-tree/neo-tree.nvim", enabled = false },
	{ "ggandor/leap.nvim", enabled = false },
	{ "ggandor/flit.nvim", enabled = false },
	{ "folke/persistence.nvim", enabled = false },
}
