return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "astro-language-server",
      "bash-language-server",
      "clangd",
      "css-lsp",
      "cssmodules-language-server",
      "deno",
      "diagnostic-languageserver",
      "emmet-ls",
      "flake8",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "luacheck",
      "prettierd",
      "shellcheck",
      "shfmt",
      "stylelint-lsp",
      "stylua",
      "svelte-language-server",
      "tailwindcss-language-server",
      "typescript-language-server",
      "unocss-language-server",
      "vue-language-server",
      "write-good",
      "proselint",
      "gitlint",
    },
  },
}
