if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
  exec tmux
fi

autoload -U colors && colors
eval "$(starship init zsh)"

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' rehash true
zstyle ':completion:*' accept-exact '*(N)'
WORDCHARS=${WORDCHARS//\/[&.;]}

autoload -Uz compinit
compinit

function downloadFile () {
  cd ~/Downloads
  aria2c $argv
  ls -lah ~/Downloads
  cd -
}
alias dl="downloadFile"

function wifiDriverEnable() {
  sudo sh -c "modprobe mt7921e ; echo 14c3 0608 > /sys/bus/pci/drivers/mt7921e/new_id"
}
alias wf='wifiDriverEnable'

alias cpf='wl-copy'
# alias cpf='xclip -sel clip'
alias reload='source ~/.zshrc ; tmux source-file ~/.tmux.conf'
alias h='htop'
alias q='exit'
alias p='ipython3'
alias ka='killall'
alias 777='chmod -R 777'
alias x='chmod +x'
alias colorPicker='zenity --color-selection'
alias cat='bat'
alias updateApplications='sudo ln -sf ~/dotfiles/applications/* /usr/share/applications/'
alias fak='git stash &>/dev/null; git stash clear'
alias t='trash'

function updateZshPlugin() {
  if hash cowsay 2>/dev/null; then
    cowsay "update zsh plugin"
  else
    echo "update zsh plugin"
  fi

  cd ~/dotfiles/zsh/functions/fzf-zsh-completions/
  git pull --force
  cd -

  cd ~/dotfiles/zsh/functions/fzf-tab/
  git pull --force
  cd -

  cd ~/dotfiles/zsh/functions/zsh-syntax-highlighting/
  git pull --force
  cd -
}

function update() {
  topgrade

  updateDnsNoMessage

  nvim -c "PlugUpdate | qa"

  updateZshPlugin
}

function hi () {
  browserDaily
  update
  neofetch
}

source ~/dotfiles/zsh/functions/dir.zsh

source ~/dotfiles/zsh/functions/arch.zsh
source ~/dotfiles/zsh/functions/debian.zsh
source ~/dotfiles/zsh/functions/fedora.zsh

source ~/dotfiles/zsh/functions/gitConfig.zsh
source ~/dotfiles/zsh/functions/fzfConfig.zsh
source ~/dotfiles/zsh/functions/fzfKeyBindings.zsh
source ~/dotfiles/zsh/functions/completion.zsh

source ~/dotfiles/zsh/functions/browserConfig.zsh
source ~/dotfiles/zsh/functions/dev.zsh
source ~/dotfiles/zsh/functions/dns.zsh
source ~/dotfiles/zsh/functions/gnome.zsh
source ~/dotfiles/zsh/functions/history.zsh
source ~/dotfiles/zsh/functions/media.zsh
source ~/dotfiles/zsh/functions/note.zsh
source ~/dotfiles/zsh/functions/path.zsh
source ~/dotfiles/zsh/functions/tmux.zsh
source ~/dotfiles/zsh/functions/vimMode.zsh
source ~/dotfiles/zsh/functions/virt.zsh

source ~/dotfiles/zsh/functions/zshAutoSuggestions.zsh
source ~/dotfiles/zsh/functions/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source ~/dotfiles/zsh/functions/commandStartupShell.zsh
