if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
  exec tmux
fi

autoload -U colors && colors

eval "$(starship init zsh)"

command_not_found_handler () {
  TF_SHELL_ALIASES=$(alias);
  TF_CMD=$(
  export TF_SHELL_ALIASES;
  export TF_SHELL=zsh;
  export TF_ALIAS=fuck;
  export TF_HISTORY="$@";
  export PYTHONIOENCODING=utf-8;
  thefuck THEFUCK_ARGUMENT_PLACEHOLDER
  ) && eval $TF_CMD;
  test -n "$TF_CMD" && print -s $TF_CMD;
}

if hash thefuck 2>/dev/null; then
  command_not_found_handler
else
  if hash apt 2>/dev/null; then
    sudo apt install thefuck -y
  fi
  if hash dnf 2>/dev/null; then
    sudo dnf -y install thefuck
  fi
  if hash pacman 2>/dev/null; then
    sudo pacman -S --noconfirm thefuck
  fi

  command_not_found_handler
fi

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' rehash true
zstyle ':completion:*' accept-exact '*(N)'
WORDCHARS=${WORDCHARS//\/[&.;]}

autoload -Uz compinit
compinit

alias reload='source ~/.zshrc ; tmux source-file ~/.tmux.conf'
alias h='htop'
alias q='exit'
alias p='ipython3'
alias ka='killall'
alias 777='chmod -R 777'
alias x='chmod +x'
alias colorPicker='zenity --color-selection'
alias cat='bat'
alias fak='git stash &>/dev/null; git stash clear'
alias t='trash'

function hi () {
  browserDaily
  update
  neofetch
}

function downloadFile () {
  cd ~/Downloads
  aria2c $argv
  ls -lah ~/Downloads
  cd -
}
alias dl="downloadFile"

function wifiDriverEnable() {
  sudo sh -c "modprobe mt7921e ; echo 14c3 0608 > /sys/bus/pci/drivers/mt7921e/new_id"
}
alias wf='wifiDriverEnable'

# for debian base
if hash apt 2>/dev/null; then
  alias ins='sudo apt install -y'
  alias inss='apt search'
  alias uins='sudo apt remove -y'
fi

# for fedora
if hash dnf 2>/dev/null; then
  alias ins='sudo dnf -y install'
  alias inss='dnf search'
  alias uins='sudo dnf -y remove'
fi

# for arch base
if hash pacman 2>/dev/null; then
  alias ins='sudo pacman -S --noconfirm'
  alias inss='pacman -Ss'
  alias ya='yay --noconfirm'
  alias uins='sudo pacman -Rs --noconfirm'

  function switchToJava8() {
    sudo archlinux-java set java-8-openjdk
    archlinux-java status
  }

  function switchToJava11() {
    sudo archlinux-java set java-8-openjdk
    archlinux-java status
  }

  function switchToJava17() {
    sudo archlinux-java set java-17-openjdk
    archlinux-java status
  }
fi

if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
  alias copy='wl-copy'
else
  alias copy='xclip -sel clip'
fi

alias delete_all_symbolic_links_current_dir='sudo find -type l -delete'

updateApplications() {
  cd /usr/share/applications/
  sudo find -type l -delete
  cd -
  sudo ln -sf ~/dotfiles/applications/* /usr/share/applications/
}

source ~/dotfiles/zsh/functions/dir.zsh

source ~/dotfiles/zsh/functions/gitConfig.zsh
source ~/dotfiles/zsh/functions/fzfConfig.zsh
source ~/dotfiles/zsh/functions/fzfKeyBindings.zsh
source ~/dotfiles/zsh/functions/completion.zsh

source ~/dotfiles/zsh/functions/browserConfig.zsh
source ~/dotfiles/zsh/functions/cowsay.zsh
source ~/dotfiles/zsh/functions/dev.zsh
source ~/dotfiles/zsh/functions/update.zsh
source ~/dotfiles/zsh/functions/gnome.zsh
source ~/dotfiles/zsh/functions/history.zsh
source ~/dotfiles/zsh/functions/media.zsh
source ~/dotfiles/zsh/functions/path.zsh
source ~/dotfiles/zsh/functions/tmux.zsh
source ~/dotfiles/zsh/functions/vim.zsh
source ~/dotfiles/zsh/functions/virt.zsh

source ~/dotfiles/zsh/functions/zshAutoSuggestions.zsh
source ~/dotfiles/zsh/functions/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source ~/dotfiles/zsh/functions/commandStartupShell.zsh
