#!/bin/bash

alias reload='source ~/.bashrc ; tmux source-file ~/.tmux.conf'
alias ka='killall'
alias cat='bat'
alias t='trash'
alias q='exit'
alias owa='code .'
alias se='sudoedit'
alias x='chmod +x'

alias ins='sudo dnf install -y'
alias uins='sudo dnf remove -y'
inss() {
  dnf search $1
  flatpak search $1
}

browser_daily() {
  xdg-open "https://facebook.com"
  xdg-open "https://mail.google.com/mail/u/0/#inbox"
  xdg-open "https://mail.google.com/mail/u/1/#inbox"
  xdg-open "https://www.youtube.com/feed/subscriptions"
  xdg-open "https://feeder.co/reader"
}

hi() {
  browser_daily
  neofetch
}

alias ..='cd .. ; l'
alias ...='cd .. ; cd .. ; l'
alias dow='cd ~/Downloads ; l'
alias doc='cd ~/Documents ; l'
alias tmp='cd /tmp'
alias changeDirToUsbFolder='cd /run/media/master/ ; ls'

alias ls='exa --long --all --icons --git'
alias l='ls'
alias sl='ls'
alias ll='ls'
alias la='exa --all --icons'
alias al='la'

alias mk="make_dir"
