#!/usr/bin/env bash

alias reload='source ~/.bashrc ; tmux source-file ~/.tmux.conf'
alias ka='killall'
alias cat='bat'
alias t='trash'
alias q='exit'
alias owa='code .'
alias se='sudoedit'
alias x='chmod +x'
alias h='htop'
alias winget='winget.exe'
alias pwsh='pwsh.exe'
alias wsl='wsl.exe'

alias ins='sudo apt install -y'
alias uins='sudo apt remove -y'
inss() {
  apt search $1
  winget search $1
}

browser_daily() {
  xdg-open "https://facebook.com"
  xdg-open "https://mail.google.com/mail/u/0/#inbox"
  xdg-open "https://mail.google.com/mail/u/1/#inbox"
  xdg-open "https://www.youtube.com/feed/subscriptions"
  xdg-open "https://feeder.co/reader"
}

hi() {
  browser_daily
  neofetch
}

alias ..='cd .. ; l'
alias ...='cd .. ; cd .. ; l'
alias dow='cd ~/Downloads ; l'
alias doc='cd ~/Documents ; l'
alias tmp='cd /tmp'
alias changeDirToUsbFolder='cd /run/media/master/ ; ls'

alias ls='exa --long --all --icons'
alias l='ls'
alias sl='ls'
alias ll='ls'
alias la='exa --all --icons'
alias al='la'

make_dir() {
  if [ ! -n "$1" ]; then
    echo -n "👉 Enter a directory name"
    read dirName
    mkdir -p $dirName
    cd $dirName
  elif [ -d $1 ]; then
    echo -e "👉 $1 already exists"
    cd $1
  else
    mkdir -p $1
    cd $1
  fi
}
alias mk="make_dir"
