#!/bin/bash

source ~/dotfiles/bash/start
source ~/dotfiles/bash/env
source ~/dotfiles/bash/option
source ~/dotfiles/bash/alias
source ~/dotfiles/bash/dev
source ~/dotfiles/bash/fzf
source ~/dotfiles/bash/tmux
source ~/dotfiles/bash/media
