#!/usr/bin/env bash

[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] &&
  . /usr/share/bash-completion/bash_completion

source ~/dotfiles/bash/completion_gh
source ~/dotfiles/bash/completion_fzf

bind -x '"\t": fzf_bash_completion'

update_bash_functions() {
  gh completion -s bash >~/dotfiles/bash/completion_gh
  curl https://raw.githubusercontent.com/lincheney/fzf-tab-completion/master/bash/fzf-bash-completion.sh > ~/dotfiles/bash/completion_fzf
}
