#!/usr/bin/env bash

SERVER_IP() {
  hostname -I
}

ser() {
  browser-sync start --server --files . --no-notify --host SERVER_IP --port 9000
}

change_dir_to_git_root() {
  cd $(git rev-parse --show-toplevel)
}
alias cdr='change_dir_to_git_root'

git_status() {
  git status -sb
}
alias st='git_status'

auto_commit() {
  git add --all
  git commit -m "[👌Auto commit] $(curl -s whatthecommit.com/index.txt)"
}

ok() {
  st
  auto_commit
  git push
}

go_to_git_clone_repo_dir() {
  gitDir="$(basename "$1" .git)"
  gitDirResolved=${2:-$gitDir}
  git clone "$@" && cd "$gitDirResolved"
}
alias gc='go_to_git_clone_repo_dir'

yo() {
  git diff
  echo -n "👉 Commmit message: "
  read "commitMessage"
  git add --all
  git commit -m "$commitMessage"
  git push
}

function auto_sync {
  repo=(
    /home/master/repos/thuanOwa/ok
    /home/master/repos/thuanOwa/obs-studio
    /home/master/repos/thuanOwa/co_so_du_lieu
    /home/master/repos/thuanOwa/dataLab
    /home/master/repos/thuanOwa/ky_thuat_lap_trinh
    /home/master/repos/thuanOwa/lap_trinh_huong_doi_tuong
    /home/master/repos/thuanOwa/nhap_mon_cau_truc_du_lieu
    /home/master/repos/thuanOwa/nhap_mon_web_va_ung_dung
    /home/master/repos/thuanOwa/thuc-hanh-ky-thuat-lap-trinh
    /home/master/repos/thuanOwa/thuc-hanh-lap-trinh-huong-doi-tuong
    /home/master/repos/thuanOwa/thuc-hanh-nhap-mon-cau-truc-du-lieu
    /home/master/repos/thuanOwa/thuc-hanh-nhap-mon-web-va-ung-dung
    /home/master/repos/thuanOwa/thuc_thanh_nhap_mon_lap_trinh
    /home/master/repos/thuanOwa/ublock_adblock_list
    /home/master/repos/thuanOwa/cong_nghe_phan_mem
    /home/master/repos/thuanOwa/thuan_ublacklist
    /home/master/repos/thuanOwa/lap_trinh_ung_dung_co_so_du_lieu
    /home/master/repos/thuanOwa/quan_tri_co_so_du_lieu
    /home/master/repos/thuanOwa/ma_hoa_ung_dung
    /home/master/repos/thuanOwa/img
    /home/master/repos/thuanOwa/lap_trinh_cho_thiet_bi_di_dong/
    /home/master/repos/thuanOwa/lap_trinh_web/
    /home/master/repos/thuanOwa/phat_trien_phan_mem_nguon_mo/
  )

  for i in ${repo[*]}; do
    cd "$i"
    pwd
    auto_commit
    git push
  done
}

function update_all_repo() {
  for dir in ~/repos/thuanOwa/*; do
    cd "$dir"
    pwd
    git pull
    git push
    cd - >/dev/null
  done

  for dir in ~/repos/OngDev/*; do
    cd "$dir"
    pwd
    git pull
    git push
    cd - >/dev/null
  done

  for dir in ~/repos/isekaiSystem/*; do
    cd "$dir"
    pwd
    git pull
    git push
    cd - >/dev/null
  done

  repoNotInDefaultDir=(
    ~/dotfiles/
    ~/repos/OngDev/.github/
  )

  for i in ${repoNotInDefaultDir[*]}; do
    cd "$i"
    pwd
    git pull
    git push
    cd - >/dev/null
  done
}
