#!/usr/bin/env bash

alias yt="yt-dlp -f bestvideo+bestaudio"

yta() {
  yt-dlp -f "bestaudio" --continue --no-overwrites --ignore-errors --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s"
}

alias m='mpv --shuffle --loop-playlist ~/Music/*'

update_music() {
  local music_dir
  music_dir=$HOME/Music/music_i_like/

  trash $music_dir
  mkdir -p $music_dir
  cd $music_dir

  yt-dlp -f "bestaudio" --continue --no-overwrites --ignore-errors --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" "https://www.youtube.com/playlist?list=PLcazFfFZIFPld2xu_nAgmbgj5QldQOpUB"

  cd -
}
